#
# Travis configuration
#

# Source related
language: cpp
# Defined in CXX
compiler:
    - gcc
    - clang

before_install: "sudo ./scripts/install_gtest.sh"
install: "cd cpp && make && cd .."
script: "cd cpp && make check && cd .."

# Branches
branches:
    only:
        - master
        - next
        - util/testing
